import fs from "node:fs/promises";
import path from "node:path";
import { ResourceTemplate } from "@modelcontextprotocol/sdk/server/mcp.js";
import { listVerseFiles, readVerseFile, resolveProject, verseFileDescriptor, decodeVerseFileUri } from "./project.mjs";

export class ResourceStore {
  constructor(config) {
    this.config = config;
    this.generated = new Map();
  }

  addJson(prefix, value, metadata = {}) {
    const id = metadata.id ?? createId(prefix);
    const uri = `uefn://${prefix}/${encodeURIComponent(id)}`;
    this.generated.set(uri, {
      uri,
      id,
      kind: "json",
      mimeType: "application/json",
      value,
      metadata,
      createdAt: new Date().toISOString()
    });
    return uri;
  }

  addText(prefix, text, metadata = {}) {
    const id = metadata.id ?? createId(prefix);
    const uri = `uefn://${prefix}/${encodeURIComponent(id)}`;
    this.generated.set(uri, {
      uri,
      id,
      kind: "text",
      mimeType: metadata.mimeType ?? "text/plain",
      value: text,
      metadata,
      createdAt: new Date().toISOString()
    });
    return uri;
  }

  addFile(uri, filePath, metadata = {}) {
    this.generated.set(uri, {
      uri,
      kind: "file",
      mimeType: metadata.mimeType ?? guessMimeType(filePath),
      filePath,
      metadata,
      createdAt: new Date().toISOString()
    });
    return uri;
  }

  async read(uri) {
    const generated = this.generated.get(uri);
    if (generated) {
      return await this.readGenerated(generated);
    }

    const project = await resolveProject(this.config);
    const verseFile = decodeVerseFileUri(uri);
    if (verseFile !== null) {
      const result = await readVerseFile(project, verseFile);
      return textResource(uri, result.content, "text/plain");
    }

    if (uri === "uefn://project/summary") {
      return textResource(uri, JSON.stringify({
        projectPath: project.projectPath,
        contentPath: project.contentPath,
        compatibilityVersion: project.compatibilityVersion,
        versePath: project.versePath,
        pythonEnabled: project.pythonEnabled
      }, null, 2), "application/json");
    }

    throw new Error(`Unknown UEFN resource URI: ${uri}`);
  }

  async readGenerated(resource) {
    if (resource.kind === "json") {
      return textResource(resource.uri, JSON.stringify(resource.value, null, 2), resource.mimeType);
    }
    if (resource.kind === "text") {
      return textResource(resource.uri, resource.value, resource.mimeType);
    }
    if (resource.kind === "file") {
      const data = await fs.readFile(resource.filePath);
      return {
        contents: [
          {
            uri: resource.uri,
            mimeType: resource.mimeType,
            blob: data.toString("base64")
          }
        ]
      };
    }
    throw new Error(`Unknown generated resource kind: ${resource.kind}`);
  }

  listGeneratedResources() {
    return [...this.generated.values()].map((resource) => ({
      uri: resource.uri,
      name: resource.metadata.name ?? resource.id ?? path.basename(resource.filePath ?? resource.uri),
      title: resource.metadata.title,
      mimeType: resource.mimeType
    }));
  }
}

export function registerUefnResources(server, config, store) {
  server.registerResource(
    "uefn_project_summary",
    "uefn://project/summary",
    {
      title: "UEFN project summary",
      description: "Compact summary of the configured UEFN project.",
      mimeType: "application/json"
    },
    async (uri) => store.read(uri.toString())
  );

  server.registerResource(
    "uefn_verse_file",
    new ResourceTemplate("uefn://verse/file/{encodedRelativePath}", {
      list: async () => {
        if (!config.projectPath) {
          return { resources: [] };
        }
        const project = await resolveProject(config);
        const files = await listVerseFiles(project.contentPath);
        return {
          resources: files.map((file) => {
            const descriptor = verseFileDescriptor(project.contentPath, file);
            return {
              uri: descriptor.resourceUri,
              name: descriptor.relativePath,
              title: descriptor.relativePath,
              mimeType: "text/plain"
            };
          })
        };
      }
    }),
    {
      title: "Verse file",
      description: "A Verse source file from the configured UEFN project.",
      mimeType: "text/plain"
    },
    async (uri) => store.read(uri.toString())
  );

  server.registerResource(
    "uefn_generated_resource",
    new ResourceTemplate("uefn://{kind}/{id}", {
      list: async () => ({ resources: store.listGeneratedResources() })
    }),
    {
      title: "Generated UEFN MCP artifact",
      description: "Snapshots, visual captures, logs, and Python dry-run records generated by tools."
    },
    async (uri) => store.read(uri.toString())
  );
}

function textResource(uri, text, mimeType) {
  return {
    contents: [
      {
        uri,
        mimeType,
        text
      }
    ]
  };
}

function createId(prefix) {
  return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
}

function guessMimeType(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  if (ext === ".png") {
    return "image/png";
  }
  if (ext === ".jpg" || ext === ".jpeg") {
    return "image/jpeg";
  }
  if (ext === ".json") {
    return "application/json";
  }
  return "application/octet-stream";
}
